"""empty message

Revision ID: 42abf2c4cb40
Revises: 2ca22da1a03c
Create Date: 2022-11-19 16:43:54.715564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42abf2c4cb40'
down_revision = '2ca22da1a03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_password_uuid', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_password_uuid')

    # ### end Alembic commands ###
